swagger: "2.0"
info:
  description: beego Test API
  version: 1.0.0
basePath: /v1
paths:
  /user/auth:
    get:
      tags:
      - user
      description: 测试错误码
      operationId: UserController.认证测试
      responses:
        "200":
          description: '{string}'
        "401":
          description: unauthorized
  /user/login:
    post:
      tags:
      - user
      description: 账号登录接口
      operationId: UserController.登录
      parameters:
      - in: formData
        name: username
        description: 用户昵称
        required: true
        type: string
      - in: formData
        name: password
        description: 密码
        required: true
        type: string
      responses:
        "200":
          description: '{string}'
        "401":
          description: No Admin
  /user/reg:
    post:
      tags:
      - user
      description: 用户注册
      operationId: UserController.注册新用户
      parameters:
      - in: formData
        name: phone
        description: 用户手机号
        required: true
        type: string
      - in: formData
        name: username
        description: 用户昵称
        required: true
        type: string
      - in: formData
        name: password
        description: 密码
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.StaffUser'
        "403":
          description: 参数错误：缺失或格式错误
definitions:
  models.StaffUser:
    title: StaffUser
    type: object
    properties:
      city:
        type: string
      create_at:
        type: string
        format: datetime
      email:
        type: string
      id:
        type: integer
        format: int64
      username:
        type: string
      phone:
        type: string
